apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ljy2tty6m-nodejs 
  janus-idp.io/tekton: ljy2tty6m-nodejs
  backstage.io/kubernetes-id: ljy2tty6m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ljy2tty6m-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  